// HTTP Server refactored with modular architecture - Ollama Easy GUI v1.0
const http = require('http');
const fs = require('fs');
const path = require('path');

// Import controllers
const ChatController = require('./controllers/ChatController');
const ModelController = require('./controllers/ModelController');
const OllamaController = require('./controllers/OllamaController');
const MCPController = require('./controllers/MCPController');
const LogController = require('./controllers/LogController');

// Import core modules
const OllamaManager = require('./core/ollama/OllamaManager');
const ChatStorage = require('./core/storage/ChatStorage');
const logger = require('./core/logging/LoggingService');

// PHASE 4B.1: Security Enhancement
const SecurityValidator = require('./security/SecurityValidator');

// Configuration
const PORT = 3003;

// Initialize controllers
const mcpController = new MCPController();
const chatController = new ChatController(null, null, null, mcpController);
const modelController = new ModelController();
const ollamaController = new OllamaController(null, null, mcpController);

// Main managers for global functions
const ollamaManager = new OllamaManager();
const chatStorage = new ChatStorage();

// WebSocket clients for real-time notifications
const clients = [];

// Main router
class Router {
    constructor() {
        this.routes = [];
    }

    // Register a route
    route(method, path, handler) {
        this.routes.push({ method, path, handler });
    }

    // Find and execute the appropriate route
    async handleRequest(req, res) {
        const { method, url } = req;

        // PHASE 4B.1: Security validation middleware
        try {
            SecurityValidator.validateRequest(req);
        } catch (error) {
            console.error('🚨 Security validation failed:', error.message);
            const statusCode = error.message.includes('Rate limit') ? 429 : 400;
            res.writeHead(statusCode, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success: false, error: error.message }));
            return true;
        }

        // Handle OPTIONS for CORS
        if (method === 'OPTIONS') {
            res.writeHead(200);
            res.end();
            return true;
        }

        // Search for exact route
        const exactRoute = this.routes.find(route => 
            route.method === method && route.path === url
        );

        if (exactRoute) {
            await exactRoute.handler(req, res);
            return true;
        }

        // Search for route with pattern (startsWith)
        const patternRoute = this.routes.find(route =>
            route.method === method && url.startsWith(route.path)
        );

        if (patternRoute) {
            await patternRoute.handler(req, res);
            return true;
        }

        return false; // Route not found
    }
}

// Initialize router
const router = new Router();

// ========== CHAT ROUTES ==========
router.route('POST', '/api/chat/new', (req, res) => chatController.createChat(req, res));
router.route('GET', '/api/chat/list', (req, res) => chatController.listChats(req, res));
router.route('GET', '/api/chat/load/', (req, res) => chatController.loadChat(req, res));
router.route('DELETE', '/api/chat/delete/', (req, res) => chatController.deleteChat(req, res));
router.route('POST', '/api/chat/update/', (req, res) => chatController.updateChat(req, res));
router.route('GET', '/api/chat/stats', (req, res) => chatController.getStats(req, res));
router.route('POST', '/api/chat/cleanup', (req, res) => chatController.cleanupChats(req, res));
router.route('POST', '/api/chat/upload/', (req, res) => chatController.uploadAttachment(req, res));
router.route('GET', '/api/chat/attachment/', (req, res) => chatController.getAttachment(req, res));
router.route('GET', '/api/chat/attachments/', (req, res) => chatController.listAttachments(req, res));
router.route('GET', '/api/chats/', (req, res) => chatController.listChatAttachments(req, res));
router.route('POST', '/api/chat/add-attachments', (req, res) => chatController.addAttachments(req, res));
// Test endpoint for debug download
router.route('POST', '/api/chat/download-test', (req, res) => {
    console.log('📥 Download test endpoint called');
    const content = `# Test Download\n\nThis is a download test.\n\n**Date**: ${new Date().toLocaleString()}\n\n---\n*Generated by Ollama Easy GUI*`;
    
    res.writeHead(200, {
        'Content-Type': 'text/markdown',
        'Content-Disposition': 'attachment; filename="test_download.md"',
        'Content-Length': Buffer.byteLength(content)
    });
    res.end(content);
});

router.route('POST', '/api/chat/download-message', (req, res) => chatController.downloadMessage(req, res));
router.route('POST', '/api/chat/send', (req, res) => ollamaController.sendChatMessage(req, res));
router.route('POST', '/api/chat/send-stream', (req, res) => ollamaController.sendChatMessageStream(req, res)); // Real-time streaming

// ========== MODEL ROUTES ==========
router.route('POST', '/api/models/download', (req, res) => modelController.downloadModel(req, res));
router.route('GET', '/api/models/download-progress/', (req, res) => modelController.getDownloadProgress(req, res));
router.route('DELETE', '/api/models/remove/', (req, res) => modelController.removeModel(req, res));
router.route('POST', '/api/models/search', (req, res) => modelController.searchModels(req, res));
router.route('GET', '/api/models/list', (req, res) => modelController.listLocalModels(req, res));
router.route('GET', '/api/models/info/', (req, res) => modelController.getModelInfo(req, res));

// ========== SYSTEM PROMPT ROUTES ==========
router.route('GET', '/api/system-prompts/list', (req, res) => ollamaController.getSystemPrompts(req, res));
router.route('POST', '/api/system-prompts/save', (req, res) => ollamaController.saveSystemPrompt(req, res));
router.route('DELETE', '/api/system-prompts/delete/', (req, res) => ollamaController.deleteSystemPrompt(req, res));

// ========== SYSTEM ROUTES ==========
router.route('POST', '/api/shutdown', (req, res) => {
    console.log('🛑 Shutdown requested via API...');
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ success: true, message: 'Server shutting down...' }));
    
    setTimeout(() => {
        console.log('🛑 Server shutting down by user request...');
        ollamaManager.stopMonitoring();
        process.exit(0);
    }, 500);
});

// ========== MCP ROUTES ==========
router.route('GET', '/api/mcp/status', (req, res) => mcpController.getStatus(req, res));
router.route('GET', '/api/mcp/tools', (req, res) => mcpController.getAvailableTools(req, res));
router.route('POST', '/api/mcp/execute-tool', (req, res) => mcpController.executeTool(req, res));
router.route('POST', '/api/mcp/reload-config', (req, res) => mcpController.reloadConfiguration(req, res));
router.route('GET', '/api/mcp/servers', (req, res) => mcpController.getServers(req, res));
router.route('POST', '/api/mcp/test-integration', (req, res) => mcpController.testIntegration(req, res));
router.route('DELETE', '/api/mcp/disconnect', (req, res) => mcpController.disconnect(req, res));
router.route('POST', '/api/mcp/toggle-server', (req, res) => mcpController.toggleServer(req, res));
router.route('GET', '/api/mcp/tools-for-ollama', (req, res) => mcpController.getToolsForOllama(req, res));

// ========== LOG ROUTES ==========
router.route('GET', '/api/logs/files', (req, res) => LogController.getLogFiles(req, res));
router.route('GET', '/api/logs/stats', (req, res) => LogController.getLogStats(req, res));
router.route('GET', '/api/logs/read/', (req, res) => {
    const filename = req.url.replace('/api/logs/read/', '').split('?')[0];
    LogController.readLogFile(req, res, filename);
});
router.route('GET', '/api/logs/category/', (req, res) => {
    const category = req.url.replace('/api/logs/category/', '').split('?')[0];
    LogController.getLogsByCategory(req, res, category);
});
router.route('POST', '/api/logs/clear', (req, res) => LogController.clearLogs(req, res));
router.route('DELETE', '/api/logs/clear', (req, res) => LogController.clearLogs(req, res));

// ========== OLLAMA ROUTES ==========
router.route('GET', '/api/ollama/model-progress/', (req, res) => ollamaController.getModelProgress(req, res));
router.route('POST', '/api/ollama/warmup', (req, res) => ollamaController.warmupModel(req, res));
router.route('GET', '/api/ollama/health', (req, res) => ollamaController.getHealth(req, res));
router.route('GET', '/api/ollama/models', (req, res) => ollamaController.getLocalModels(req, res));
router.route('GET', '/api/ollama/status', (req, res) => ollamaController.getStatus(req, res));
router.route('POST', '/api/ollama/start', (req, res) => ollamaController.startOllama(req, res));
router.route('POST', '/api/ollama/start-legacy', (req, res) => ollamaController.startOllamaLegacy(req, res));
router.route('GET', '/api/ollama/stop', (req, res) => ollamaController.stopOllama(req, res));
router.route('POST', '/api/ollama/stop', (req, res) => ollamaController.stopOllama(req, res));

// ========== PROXY ROUTE ==========
// General proxy for Ollama (must be after specific routes)
router.route('GET', '/api/ollama/proxy/', (req, res) => ollamaController.proxyToOllama(req, res));
router.route('POST', '/api/ollama/proxy/', (req, res) => ollamaController.proxyToOllama(req, res));
router.route('PUT', '/api/ollama/proxy/', (req, res) => ollamaController.proxyToOllama(req, res));
router.route('DELETE', '/api/ollama/proxy/', (req, res) => ollamaController.proxyToOllama(req, res));

// ========== SERVER-SENT EVENTS ==========
router.route('GET', '/api/events', (req, res) => {
    // Setup Server-Sent Events for real-time notifications
    res.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Cache-Control'
    });

    // Add client to list with ID for tracking
    const clientId = Date.now();
    const client = { id: clientId, res };
    clients.push(client);
    console.log(`📡 SSE client connected: ${clientId}`);

    // Remove client when disconnected
    req.on('close', () => {
        const index = clients.findIndex(c => c.id === clientId);
        if (index !== -1) {
            clients.splice(index, 1);
            console.log(`📡 SSE client disconnected: ${clientId}`);
        }
    });

    // Send connection message
    res.write(`data: ${JSON.stringify({
        type: 'connected',
        message: 'SSE connection established',
        timestamp: new Date().toISOString()
    })}\n\n`);
});

// ========== STATIC FILES ==========
// Function to handle static files
async function serveStaticFile(req, res) {
    try {
        let filePath = req.url;

        // Main routes for static files
        if (filePath === '/' || filePath === '/index.html') {
            filePath = '../frontend/index.html';
        } else if (filePath.startsWith('/js/')) {
            filePath = `../frontend${filePath}`;
        } else if (filePath.startsWith('/css/')) {
            filePath = `../frontend${filePath}`;
        } else if (filePath === '/styles.css') {
            filePath = '../frontend/styles.css';
        } else if (filePath.startsWith('/icon/')) {
            filePath = `../../${filePath}`;
        } else if (filePath === '/app.js') {
            filePath = '../frontend/app.js';
        } else {
            // File not found
            res.writeHead(404);
            res.end('File not found');
            return;
        }

        const fullPath = path.join(__dirname, filePath);
        const content = fs.readFileSync(fullPath);

        // Determine content type
        const ext = path.extname(fullPath);
        let contentType = 'text/html';
        if (ext === '.js') contentType = 'text/javascript';
        else if (ext === '.css') contentType = 'text/css';
        else if (ext === '.json') contentType = 'application/json';
        else if (ext === '.png') contentType = 'image/png';
        else if (ext === '.svg') contentType = 'image/svg+xml';
        else if (ext === '.ico') contentType = 'image/x-icon';
        
        res.writeHead(200, { 'Content-Type': contentType });
        res.end(content);
    } catch (error) {
        res.writeHead(404);
        res.end('File not found');
    }
}

// ========== MAIN SERVER ==========
const server = http.createServer(async (req, res) => {
    // CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE, PUT, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    console.log(`${req.method} ${req.url}`);

    try {
        // Try to handle as API route
        const routeHandled = await router.handleRequest(req, res);

        if (!routeHandled) {
            // If not an API route, serve static files
            await serveStaticFile(req, res);
        }
    } catch (error) {
        console.error('❌ Server error:', error);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ 
            success: false, 
            error: 'Internal server error' 
        }));
    }
});

// ========== BROADCAST FUNCTIONS ==========
function broadcastToClients(message) {
    const data = `data: ${JSON.stringify(message)}\n\n`;
    clients.forEach(client => {
        try {
            client.res.write(data);
        } catch (error) {
            // Remove disconnected clients
            const index = clients.indexOf(client);
            if (index !== -1) {
                clients.splice(index, 1);
            }
        }
    });
}

// Setup callbacks for real-time notifications
ollamaManager.onStatusChange((status, message, details) => {
    broadcastToClients({
        type: 'ollamaStatus',
        status: status,
        message: message,
        details: details,
        timestamp: new Date().toISOString()
    });
});

// ========== UTILITY FUNCTIONS ==========
function openBrowser(url) {
    const { exec } = require('child_process');
    const command = process.platform === 'win32' ? `start ${url}` : 
                   process.platform === 'darwin' ? `open ${url}` : `xdg-open ${url}`;
    
    exec(command, (error) => {
        if (error) {
            console.log(`⚠️ Could not auto-open browser: ${error.message}`);
            console.log(`🌐 Please manually open: ${url}`);
        } else {
            console.log(`🌐 Browser opened automatically: ${url}`);
        }
    });
}

// ========== SERVER STARTUP ==========
server.listen(PORT, async () => {
    const startupMessage = `Ollama Easy GUI v1.0.0 starting on port ${PORT}`;
    console.log(`🚀 ${startupMessage}`);
    logger.app('info', startupMessage);

    console.log(`✨ Features: Modular Architecture, Auto-detection, Auto-start, Chat Storage, Privacy-First`);
    console.log(`💾 Storage location: ${chatStorage.dataPath}`);

    // Show initial storage statistics
    const stats = chatStorage.getStorageStats();
    if (stats.success) {
        console.log(`📊 Storage stats: ${stats.stats.totalChats} chats, ${stats.stats.totalMessages} messages, ${stats.stats.totalSizeMB}MB`);
        logger.app('info', 'Storage stats loaded', stats.stats);
    }

    // Show refactored architecture
    console.log(`🏗️ Architecture: ${router.routes.length} API routes registered`);
    console.log(`📦 Controllers: Chat, Model, Ollama, MCP, Log`);
    logger.app('info', `Server initialized with ${router.routes.length} routes`);

    // Start automatic monitoring
    ollamaManager.startMonitoring(5); // Check every 5 seconds

    // Try automatic Ollama startup
    console.log(`🔍 Attempting to auto-start Ollama...`);
    logger.app('info', 'Attempting to auto-start Ollama');

    setTimeout(async () => {
        const result = await ollamaManager.startOllamaServer();
        if (result) {
            console.log(`✅ Ollama started successfully - http://localhost:11434`);
            logger.app('info', 'Ollama started successfully');
        } else {
            console.log(`⚠️ Failed to start Ollama - check if it's installed`);
            logger.app('warn', 'Failed to auto-start Ollama');
        }

        // Open browser automatically after initialization
        console.log(`🌐 Opening Ollama Easy GUI in your default browser...`);
        setTimeout(() => {
            openBrowser(`http://localhost:${PORT}`);
        }, 2000); // Wait 2 seconds to ensure everything is ready

    }, 1000);
});

// ========== CLEANUP ==========
process.on('SIGINT', () => {
    console.log('\n🛑 Shutting down server...');
    logger.app('info', 'Server shutdown initiated by SIGINT');
    ollamaManager.stopMonitoring();
    ollamaManager.stopOllama();
    process.exit(0);
});

// Export per testing
module.exports = { server, router, chatController, modelController, ollamaController };